name: Java CI for Integration Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn -f integration-test/pom.xml clean install

      - name: Run tests
        run: mvn -f integration-test/pom.xml test